# -*- coding: utf-8 -*-
"""FEBhackoweek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkpGL2UOyBdiIpANFrJaC4pbsZllly8D
"""

!pip install spacy
!python -m spacy download en_core_web_sm

import spacy
import re

nlp = spacy.load("en_core_web_sm")

def extract_entities(question):

    semester = None
    course = None
    date = None

    # Regex patterns
    sem_pattern = r"SEM\s?\d"
    course_pattern = r"\b(CS|AIML|DS|IT|ME|CE)\b"

    # Extract semester
    sem_match = re.search(sem_pattern, question.upper())
    if sem_match:
        semester = sem_match.group()

    # Extract course
    course_match = re.search(course_pattern, question.upper())
    if course_match:
        course = course_match.group()

    # Extract date using NLP
    doc = nlp(question)
    for ent in doc.ents:
        if ent.label_ == "DATE":
            date = ent.text

    return {
        "Semester": semester,
        "Course": course,
        "Date": date
    }

question = "When is SEM 5 CS exam on 15 March?"

entities = extract_entities(question)

print("Extracted Entities:")
print(entities)

def chatbot_response(question):

    entities = extract_entities(question)

    semester = entities["Semester"]
    course = entities["Course"]

    if semester and course:
        return f"The exam for {course} in {semester} will be announced soon."

    elif semester:
        return f"The exam schedule for {semester} will be updated on the portal."

    else:
        return "Please specify semester or course."

question = input("Ask your question: ")

response = chatbot_response(question)

print("Chatbot:", response)

questions = [
    "When is SEM 5 CS exam?",
    "Tell me exam date for SEM 3 AIML",
    "When is DS exam on 10 April?"
]

for q in questions:
    print("Question:", q)
    print("Entities:", extract_entities(q))
    print("Response:", chatbot_response(q))
    print()



"""task 7 Context Handling for Follow-ups"""

import spacy
import re

nlp = spacy.load("en_core_web_sm")

def extract_entities(question):

    semester = None
    course = None

    sem_pattern = r"SEM\s?\d|third year|second year|first year"
    course_pattern = r"\b(CS|AIML|DS|IT|ME|CE)\b"

    sem_match = re.search(sem_pattern, question.lower())
    if sem_match:
        semester = sem_match.group()

    course_match = re.search(course_pattern, question.upper())
    if course_match:
        course = course_match.group()

    return {
        "Semester": semester,
        "Course": course
    }

context = {
    "semester": None,
    "course": None
}

def chatbot_response(question):

    global context

    entities = extract_entities(question)

    # Update context if new information is found
    if entities["Semester"]:
        context["semester"] = entities["Semester"]

    if entities["Course"]:
        context["course"] = entities["Course"]

    # Generate response using stored context
    if context["semester"] and context["course"]:
        return f"The exam for {context['course']} in {context['semester']} will be announced soon."

    elif context["semester"]:
        return f"Please specify the course for {context['semester']}."

    elif context["course"]:
        return f"Please specify the semester for {context['course']}."

    else:
        return "Please mention semester or course."

print("Chatbot started. Type 'exit' to stop.")

while True:

    question = input("You: ")

    if question.lower() == "exit":
        print("Chatbot ended.")
        break

    response = chatbot_response(question)

    print("Bot:", response)



"""TASK 8 8️⃣ Fallbacks and Handover"""

import spacy
import re

nlp = spacy.load("en_core_web_sm")

def extract_entities(question):

    semester = None
    course = None

    sem_pattern = r"SEM\s?\d|first year|second year|third year|fourth year"
    course_pattern = r"\b(CS|AIML|DS|IT|ME|CE)\b"

    sem_match = re.search(sem_pattern, question.lower())
    if sem_match:
        semester = sem_match.group()

    course_match = re.search(course_pattern, question.upper())
    if course_match:
        course = course_match.group()

    return {
        "Semester": semester,
        "Course": course
    }

context = {
    "semester": None,
    "course": None
}

supported_keywords = ["exam", "schedule", "date", "semester", "course"]

def fallback_response():

    return """
Sorry, I could not understand your question.

You can ask things like:
• When is SEM 5 exam?
• What is the exam date for AIML?
• Show exam schedule for SEM 3

If your issue is different, please contact the academic advisor:
Email: advisor@university.edu
"""

def chatbot_response(question):

    global context

    # Check if question is related to supported topics
    if not any(word in question.lower() for word in supported_keywords):
        return fallback_response()

    entities = extract_entities(question)

    if entities["Semester"]:
        context["semester"] = entities["Semester"]

    if entities["Course"]:
        context["course"] = entities["Course"]

    if context["semester"] and context["course"]:
        return f"The exam for {context['course']} in {context['semester']} will be announced soon."

    elif context["semester"]:
        return f"Please specify the course for {context['semester']}."

    elif context["course"]:
        return f"Please specify the semester for {context['course']}."

    else:
        return "Please mention semester or course."

print("University Chatbot Started (type 'exit' to stop)")

while True:

    question = input("You: ")

    if question.lower() == "exit":
        print("Chatbot ended.")
        break

    response = chatbot_response(question)

    print("Bot:", response)



def extract_entities(question):

    semester = None
    course = None

    sem_pattern = r"(sem\s*\d)|(first year|second year|third year|fourth year)"
    course_pattern = r"\b(CS|AIML|DS|IT|ME|CE)\b"

    sem_match = re.search(sem_pattern, question.lower())
    if sem_match:
        semester = sem_match.group()

    course_match = re.search(course_pattern, question.upper())
    if course_match:
        course = course_match.group()

    return {
        "Semester": semester,
        "Course": course
    }

print("University Chatbot Started (type 'exit' to stop)")

while True:

    question = input("You: ")

    if question.lower() == "exit":
        print("Chatbot ended.")
        break

    response = chatbot_response(question)

    print("Bot:", response)

"""TASK 9 9️⃣ Multichannel Deployment Mockup"""

def simulate_platform(platform, question):

    response = chatbot_response(question)

    if platform == "web":
        print("🌐 Web Chatbot")
        print("User:", question)
        print("Bot:", response)

    elif platform == "mobile":
        print("📱 Mobile App Chat")
        print("User:", question)
        print("Bot:", response)

    elif platform == "whatsapp":
        print("💬 WhatsApp Bot")
        print("User:", question)
        print("Bot:", response)

    else:
        print("Unknown platform")

question = "When is SEM 5 CS exam?"

simulate_platform("web", question)

print()

simulate_platform("mobile", question)

print()

simulate_platform("whatsapp", question)

print("Select Platform: web / mobile / whatsapp")

platform = input("Platform: ")

question = input("Ask your question: ")

simulate_platform(platform, question)

"""TASK 10  Analytics and Continuous Improvement"""

chat_logs = []

def simulate_platform(platform, question):

    response = chatbot_response(question)

    # store conversation
    chat_logs.append({
        "platform": platform,
        "question": question,
        "response": response
    })

    if platform == "web":
        print("🌐 Web Chatbot")

    elif platform == "mobile":
        print("📱 Mobile App Chat")

    elif platform == "whatsapp":
        print("💬 WhatsApp Bot")

    print("User:", question)
    print("Bot:", response)

for log in chat_logs:
    print(log)

labeled_data = []

for log in chat_logs:

    question = log["question"].lower()

    if "exam" in question:
        label = "Exam Query"

    elif "course" in question:
        label = "Course Query"

    else:
        label = "Unknown Query"

    labeled_data.append({
        "question": log["question"],
        "label": label
    })

for item in labeled_data:
    print(item)

unknown_queries = []

for item in labeled_data:
    if item["label"] == "Unknown Query":
        unknown_queries.append(item["question"])

print("Unknown Questions:")
for q in unknown_queries:
    print("-", q)

print("\nSuggested Improvements:")
print("- Add intent for hostel queries")
print("- Add intent for library information")
print("- Improve entity extraction for exam schedule")

# TASK 10: Analytics and Continuous Improvement

# Store chat logs
chat_logs = []

# Sample chatbot response function (uses previous logic)
def chatbot_response(question):

    q = question.lower()

    if "exam" in q and "sem 5" in q and "cs" in q:
        return "The exam for CS in SEM 5 will be announced soon."

    elif "exam" in q and "aiml" in q:
        return "Please specify the semester for AIML."

    elif "exam" in q:
        return "Please specify semester and course."

    else:
        return "Sorry, I could not understand your question."


# Simulate platform and log interactions
def simulate_platform(platform, question):

    response = chatbot_response(question)

    chat_logs.append({
        "platform": platform,
        "question": question,
        "response": response
    })

    print("\nPlatform:", platform)
    print("User:", question)
    print("Bot:", response)


# Example interactions
simulate_platform("web", "When is SEM 5 CS exam?")
simulate_platform("whatsapp", "When is AIML exam?")
simulate_platform("mobile", "Hostel timing?")
simulate_platform("web", "Library timing?")


# Show logs
print("\n--- Chat Logs ---")
for log in chat_logs:
    print(log)


# Label queries
labeled_data = []

for log in chat_logs:

    question = log["question"].lower()

    if "exam" in question:
        label = "Exam Query"

    elif "course" in question:
        label = "Course Query"

    else:
        label = "Unknown Query"

    labeled_data.append({
        "question": log["question"],
        "label": label
    })


print("\n--- Labeled Queries ---")
for item in labeled_data:
    print(item)


# Find unknown queries
unknown_queries = []

for item in labeled_data:
    if item["label"] == "Unknown Query":
        unknown_queries.append(item["question"])


print("\n--- Unknown Queries ---")
for q in unknown_queries:
    print("-", q)


# Suggested improvements
print("\n--- Suggested Improvements ---")
print("- Add intent for hostel queries")
print("- Add intent for library information")
print("- Improve entity extraction for exam queries")
print("- Add FAQ responses for common student questions")